-- MySQL Script generated by MySQL Workbench
-- 10/21/16 13:15:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`camiseta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`camiseta` (
  `idcamiseta` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `tamanho` VARCHAR(45) NULL,
  PRIMARY KEY (`idcamiseta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pacote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pacote` (
  `idpacote` INT NOT NULL,
  `pacote` VARCHAR(45) NULL,
  `preco` INT NULL,
  `descricao` VARCHAR(100) NULL,
  `camiseta_idcamiseta` INT NOT NULL,
  PRIMARY KEY (`idpacote`),
  INDEX `fk_pacote_camiseta1_idx` (`camiseta_idcamiseta` ASC),
  CONSTRAINT `fk_pacote_camiseta1`
    FOREIGN KEY (`camiseta_idcamiseta`)
    REFERENCES `mydb`.`camiseta` (`idcamiseta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modalidade` (
  `idmodalidade` INT NOT NULL,
  `modalidade` VARCHAR(45) NULL,
  `pacote_idpacote` INT NOT NULL,
  PRIMARY KEY (`idmodalidade`),
  INDEX `fk_modalidade_pacote1_idx` (`pacote_idpacote` ASC),
  CONSTRAINT `fk_modalidade_pacote1`
    FOREIGN KEY (`pacote_idpacote`)
    REFERENCES `mydb`.`pacote` (`idpacote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relatorio` (
  `idrelatorio` INT NOT NULL,
  PRIMARY KEY (`idrelatorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classificacao` (
  `idclassificacao` INT NOT NULL,
  `classificacao` INT NULL,
  `categoria` VARCHAR(45) NULL,
  `relatorio_idrelatorio` INT NOT NULL,
  PRIMARY KEY (`idclassificacao`),
  INDEX `fk_classificacao_relatorio1_idx` (`relatorio_idrelatorio` ASC),
  CONSTRAINT `fk_classificacao_relatorio1`
    FOREIGN KEY (`relatorio_idrelatorio`)
    REFERENCES `mydb`.`relatorio` (`idrelatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`candidato` (
  `idcandidato` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nomeCompleto` VARCHAR(45) NULL,
  `rg` VARCHAR(9) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `dataNascimento` VARCHAR(45) NULL,
  `tempoProva` VARCHAR(45) NULL,
  `passaporte` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `dadosContatoEmergencia` VARCHAR(45) NULL,
  `modalidade_idmodalidade` INT NOT NULL,
  `classificacao_idclassificacao` INT NOT NULL,
  PRIMARY KEY (`idcandidato`, `cpf`),
  INDEX `fk_candidato_modalidade1_idx` (`modalidade_idmodalidade` ASC),
  INDEX `fk_candidato_classificacao1_idx` (`classificacao_idclassificacao` ASC),
  CONSTRAINT `fk_candidato_modalidade1`
    FOREIGN KEY (`modalidade_idmodalidade`)
    REFERENCES `mydb`.`modalidade` (`idmodalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidato_classificacao1`
    FOREIGN KEY (`classificacao_idclassificacao`)
    REFERENCES `mydb`.`classificacao` (`idclassificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`corrida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`corrida` (
  `idcorrida` INT NOT NULL,
  `circuito` VARCHAR(45) NULL,
  `relatorio_idrelatorio` INT NOT NULL,
  PRIMARY KEY (`idcorrida`),
  INDEX `fk_corrida_relatorio_idx` (`relatorio_idrelatorio` ASC),
  CONSTRAINT `fk_corrida_relatorio`
    FOREIGN KEY (`relatorio_idrelatorio`)
    REFERENCES `mydb`.`relatorio` (`idrelatorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
